package org.shtrudell.common.net;

public enum MessageType {
    ADD_EMPLOYEE, DELETE_EMPLOYEE, UPDATE_EMPLOYEE, FIND_ALL_EMPLOYEES,
    ADD_DEPARTMENT, DELETE_DEPARTMENT, UPDATE_DEPARTMENT, FIND_ALL_DEPARTMENTS,
    NONE, FIND_ALL, DISCONNECT
}
